### ISSUE TITLE
(maybe bug?) undefined method `close_write' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by kyontan** [Shopify/pitchfork#99]
Hi, we have encountered the unexpected error on our environment, we have not yet identified the root-cause, so this is just a report.
After raising the error, the monitor process continue to have insufficient number of workers.
Subsequently the other workers also fails to spawn (since we terminate the workers on some condition using `after_request_complete`) so that the monitor process will finally have no worker and killed (by outside monitor).

We observed same error in 50 times across 5+ containers (out of more than 100+ containers), , hopefully this will help improve the stability 🙏 

Here is the log that the 17th-gen worker No. 2 (`worker=2 gen=17`) fails to spawn:

```console
@timestamp,log
2024-03-11 11:55:50.328,[Pitchfork] before_fork hook called
2024-03-11 11:55:50.328,[Pitchfork] worker=1 pid=9215 processed 1000 requests, triggering a refork
2024-03-11 11:55:50.370,[Pitchfork] mold pid=10074 gen=17 spawned
2024-03-11 11:55:50.370,[Pitchfork] after_mold_fork hook called
2024-03-11 11:55:50.509,[Pitchfork] worker=1 gen=16 Refork condition met, promoting ourselves
2024-03-11 11:55:51.897,[Pitchfork] worker=1 pid=9215 gen=16 exiting
2024-03-11 11:55:51.897,[Pitchfork] Sent SIGTERM to worker=1 pid=9215 gen=16
2024-03-11 11:55:51.897,[Pitchfork] Terminating old mold pid=9196 gen=16
2024-03-11 11:55:51.897,[Pitchfork] mold pid=10074 gen=17 ready
2024-03-11 11:55:51.984,[Pitchfork] mold pid=9196 gen=16 reaped (#<Process::Status: pid 9196 exit 0>)
2024-03-11 11:55:52.009,[Pitchfork] before_fork hook called
2024-03-11 11:55:52.009,[Pitchfork] worker=1 gen=17 spawning...
2024-03-11 11:55:52.009,[Pitchfork] worker=1 pid=9215 gen=16 reaped (#<Process::Status: pid 9215 exit 0>)
2024-03-11 11:55:52.054,[Pitchfork] Sent SIGTERM to worker=2 pid=9255 gen=16
2024-03-11 11:55:52.054,[Pitchfork] worker=1 pid=10102 gen=17 registered
2024-03-11 11:55:52.068,[Pitchfork] worker=2 pid=9255 gen=16 exiting
2024-03-11 11:55:52.137,[Pitchfork] worker=1 gen=17 ready
2024-03-11 11:55:52.193,[Pitchfork] worker=2 pid=9255 gen=16 reaped (#<Process::Status: pid 9255 exit 0>)
2024-03-11 11:55:53.213,[Pitchfork] before_fork hook called
2024-03-11 11:55:53.213,[Pitchfork] worker=2 gen=17 spawning...
2024-03-11 11:55:53.254,/vendor/bundle/ruby/3.2.0/gems/pitchfork-0.11.0/lib/pitchfork/message.rb:34:in `close_write': undefined method `close_write' for nil:NilClass (NoMethodError)
2024-03-11 11:55:53.254,
2024-03-11 11:55:53.254,      @socket.close_write
2024-03-11 11:55:53.254,             ^^^^^^^^^^^^
2024-03-11 11:55:53.254,    from /vendor/bundle/ruby/3.2.0/gems/pitchfork-0.11.0/lib/pitchfork/http_server.rb:561:in `after_fork_internal'
2024-03-11 11:55:53.254,    from /vendor/bundle/ruby/3.2.0/gems/pitchfork-0.11.0/lib/pitchfork/http_server.rb:582:in `block in spawn_worker'
2024-03-11 11:55:53.254,    from /vendor/bundle/ruby/3.2.0/gems/pitchfork-0.11.0/lib/pitchfork/http_server.rb:1045:in `block in fork_sibling'
2024-03-11 11:55:53.254,    from /vendor/bundle/ruby/3.2.0/gems/pitchfork-0.11.0/lib/pitchfork.rb:188:in `block in clean_fork'
2024-03-11 11:55:53.254,    from /vendor/bundle/ruby/3.2.0/gems/pitchfork-0.11.0/lib/pitchfork.rb:186:in `catch'
2024-03-11 11:55:53.254,    from /vendor/bundle/ruby/3.2.0/gems/pitchfork-0.11.0/lib/pitchfork.rb:186:in `clean_fork'
2024-03-11 11:55:53.254,    from /vendor/bundle/ruby/3.2.0/gems/pitchfork-0.11.0/lib/pitchfork/http_server.rb:593:in `spawn_initial_mold'
2024-03-11 11:55:53.254,    from /vendor/bundle/ruby/3.2.0/gems/pitchfork-0.11.0/lib/pitchfork/http_server.rb:196:in `start'
2024-03-11 11:55:53.254,    from /vendor/bundle/ruby/3.2.0/gems/pitchfork-0.11.0/exe/pitchfork:109:in `<top (required)>'
2024-03-11 11:55:53.254,    from /vendor/bundle/ruby/3.2.0/bin/pitchfork:25:in `load'
2024-03-11 11:55:53.254,    from /vendor/bundle/ruby/3.2.0/bin/pitchfork:25:in `<top (required)>'
2024-03-11 11:55:53.254,    from /vendor/bundle/ruby/3.2.0/gems/bundler-2.4.18/lib/bundler/cli/exec.rb:58:in `load'
2024-03-11 11:55:53.254,    from /vendor/bundle/ruby/3.2.0/gems/bundler-2.4.18/lib/bundler/...
2024-03-11 11:55:54.707,[Pitchfork] reaped unknown subprocess #<Process::Status: pid 10154 SIGKILL (signal 9)>
```

Environment:
- uname -a: `Linux 5.10.210-201.852.amzn2.x86_64 ...`
- Distribution: Amazon Linux 2
- Architecture: x86_64
- Ruby: Ruby 3.2.2 (2023-03-30 revision e51014f9c0) + YJIT
- Pitchfork: 0.11.0

**Comment by casperisfine** [comment]
This is really weird. I've never seen such error before.

Somehow there are `MessageSocket` instance with a `nil` `@socket`. I suggest raising in `MessageSocket#initialize` if given `nil` to try to figure out how this happened.
